name: junitreporter
version: 1.0.0
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/NishantSinghh/junit-reporter
documentation:

dependencies:
  args: ^2.1.0
  intl: ^0.17.0
  testreport: ^1.2.0
  xml: ^5.0.2

dev_dependencies:
  pedantic: ^1.11.1
  test: any

environment:
  sdk: '>=2.11.0 <3.0.0'

executables:
  tojunit: